# Generated by Django 4.2.1 on 2023-05-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id_pk', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('time', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('title_full', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
